language: java
jdk: openjdk11
services:
  - docker

before_install:
  - docker pull openjdk11-alpine
script:
  - mvn test
  - mvn clean package
  - docker build -t travis-test .
  - docker images
  - docker tag travis-test interviewdot/travis-test
  - docker push interviewdot/travis-test
