dist: xenial

services:
  - docker

language: java

jdk: openjdk11

before_install:
  - mvn clean
  - docker pull openjdk:11-jdk-alpine

install:
  - mvn -N io.takari:maven:wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V




